AppBundle\Entity\ReportType:
    type: entity
    table: report_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 15
            fixed: false
    lifecycleCallbacks: {  }
