AppBundle\Entity\Report:
    type: entity
    table: report
    indexes:
        updated_id:
            columns:
                - updated_id
        type:
            columns:
                - type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            fixed: false
        status:
            type: boolean
            nullable: false
    manyToOne:
        type:
            targetEntity: ReportType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                type:
                    referencedColumnName: id
            orphanRemoval: false
        updated:
            targetEntity: Report
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
